### ISSUE TITLE
Buttons appear flat when snapped

### ISSUE THREAD

**Issue by cliftonts** [cliftonts/rokugtk#8]
Buttons have lost their styling when run from within a snap.
![screenshot from 2017-01-17 19-51-24](https://cloud.githubusercontent.com/assets/17416309/22037662/0094e2b4-dcf0-11e6-923e-99a141d621ea.png)

**Comment by ZenHarbinger** [comment]
Gotcha, did test, merge https://github.com/cliftonts/rokugtk/pull/11 and you'll have the slick GTK2 layout.

**Comment by cliftonts** [comment]
Excellent. Now I don't suppose you have any idea to display a dialog 
without it halting my program do you? I'm trying to produce a popup 
message on startup saying it is searching for the roku but it halts the 
searching process until you close the window.

**Comment by ZenHarbinger** [comment]
I've done some GTK + python stuff.
The most I can offer you is to go through the docs for that.
I did some GTK work w/ python ages ago.
https://github.com/zenharbinger/spotipy
But haven't touched it in a LONG time.  I know there are weird threading issues in python.

**Comment by cliftonts** [comment]
It's ok. I need to come up with a solution for modifying the IP range 
anyway. It only does 192.168.0.x at the moment. I'll add the whole lot 
into the main interface, something like a little screen above the keypad.

**Comment by ZenHarbinger** [comment]
You could do a current IP(s) of the desktop/device and then cycle through.
So if you know you are IP 192.168.100.42, search all of 192.168.100.  Unless roku does a bonjour broadcast.  But if I remember right (unless changed recently); snaps don't handle avahi/bonjour properly.

**Comment by cliftonts** [comment]
Issue now resolved thanks to ZenHarbinger.
